"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_meint((euj9vp4g05uqecfr8#+b042o^400@mmatr00qtry!e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# ---------------------------------------------------------------------------
# Shelfie
# ---------------------------------------------------------------------------
import os
from dotenv import load_dotenv

load_dotenv(BASE_DIR / ".env")

INSTALLED_APPS += [
    "rest_framework",
    "corsheaders",
    "scanner",
]

MIDDLEWARE.insert(0, "corsheaders.middleware.CorsMiddleware")

# Dev only: the Expo client runs on a different origin (and on a phone).
CORS_ALLOW_ALL_ORIGINS = True
ALLOWED_HOSTS = ["*"]

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
}

# Repo root, so catalog.csv sits beside the README rather than inside backend/.
REPO_ROOT = BASE_DIR.parent
CATALOG_PATH = REPO_ROOT / "catalog.csv"

SHELFIE = {
    "VLM_MODEL": os.getenv("VLM_MODEL", "claude-sonnet-4-5"),
    "VLM_TIMEOUT_SECONDS": float(os.getenv("VLM_TIMEOUT_SECONDS", 30)),
    "VLM_MAX_RETRIES": int(os.getenv("VLM_MAX_RETRIES", 2)),
    "VLM_BATCH_SIZE": int(os.getenv("VLM_BATCH_SIZE", 6)),
    # Hard ceiling on paid reads per photo. Spines past this are surfaced as
    # skipped rather than read, so a wall-sized shelf cannot run up a bill.
    "VLM_MAX_SPINES": int(os.getenv("VLM_MAX_SPINES", 200)),
    "DETECTOR_WEIGHTS": os.getenv("DETECTOR_WEIGHTS", "yolov8n.pt"),
    "DETECTOR_IMGSZ": int(os.getenv("DETECTOR_IMGSZ", 960)),
    "DETECTOR_CONFIDENCE": float(os.getenv("DETECTOR_CONFIDENCE", 0.22)),
    # Short-edge pixels a spine crop is upscaled to before it is sent.
    "CROP_MIN_HEIGHT": int(os.getenv("CROP_MIN_HEIGHT", 220)),
    "MATCH_THRESHOLD": float(os.getenv("MATCH_THRESHOLD", 0.85)),
    "REVIEW_THRESHOLD": float(os.getenv("REVIEW_THRESHOLD", 0.55)),
}
