# Generated by Django 6.1 on 2026-08-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanitem',
            name='status',
            field=models.CharField(choices=[('matched', 'Matched'), ('review', 'Needs review'), ('unmatched', 'No catalog match'), ('unreadable', 'Could not be read'), ('skipped', 'Skipped to stay within the per-scan limit')], max_length=20),
        ),
    ]
